export const WEATHER_DESCRIPTIONS: string[] = [
    "todos",
    "cielo claro",
    "algo de nubes",
    "nubes dispersas",
    "nubes rotas",
    "muy nuboso",
    "nublado",
    "lluvia ligera",
    "lluvia moderada",
    "lluvia intensa",
    "lluvia muy intensa",
    "lluvias torrenciales",
    "llovizna ligera",
    "llovizna",
    "llovizna intensa",
    "tormentas con lluvia ligera",
    "tormentas con lluvia",
    "tormentas con lluvia intensa",
    "tormentas con granizo pequeño",
    "tormentas con granizo grande",
    "granizo",
    "lluvia congelante",
    "nieve ligera",
    "nieve",
    "nieve intensa",
    "granizo y nieve",
    "aguanieve",
    "neblina",
    "calima",
    "tormenta de arena",
    "tormenta de polvo",
    "tornado",
    "huracán",
    "bruma",
    "viento fuerte"
  ];
  